plugins {
    id 'java'
    id 'application'
}

group = 'com.ashfall'
version = '0.1.0'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

application {
    mainClass = 'com.ashfall.engine.Main'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

sourceSets {
    main {
        java {
            srcDirs = ['engine/src/main/java']
        }
    }
    test {
        java {
            srcDirs = ['engine/src/test/java']
        }
    }
}

tasks.named('test') {
    useJUnitPlatform()
}